import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import ContactUs from '../components/contactus'
import Footer from '../components/footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Horsepower</title>
        <meta name="Secret Horse Blog" content="Generated by create next app" />
        <link rel="icon" href="/secrethorse.png" />
      </Head>
      <Masthead />
      <AboutUs />
      <Skills />
      <ContactUs />
      <Footer />
     
    </div>
  )
}

export default Home
